#!/bin/sh
# Ameya Shahane
# Assignment 7.2.1 #
# April 18, 2017

# printing assignment details
echo " " # print a blank line
echo Name: Ameya Shahane
echo Assignment Number: 7.2.1
echo Due Date: April 18, 2017
echo " " # print a blank line

set -e
if [ -z "$1" ] || [ -z "$2" ] 
then
	echo "Usage: rename oldfilename newfilename"
else
	mv $1 $2
	echo $1 had been renamed $2
	echo here is a listing of the directory:
	ls
fi
