#!/bin/csh
# Ameya Shahane
# Assignment 8.2.2 #
# May 2, 2017

# printing assignment details
echo " " # print a blank line
echo Name: Ameya Shahane
echo Assignment Number: 8.2.2
echo Due Date: May 2, 2017
echo " " # print a blank line

if ("$1" == "") then 
	echo "Usage: checking loginname"
else
	set checkuser=`grep "$1" /etc/passwd`
	if ( "$checkuser" != "" ) then
		echo Found $1 in the /etc/passwd file
	else
		echo No such user on our system
	endif
endif
