#!/bin/csh
# Ameya Shahane
# Assignment 8.2.1 #
# May 2, 2017


# printing assignment details
echo " " # print a blank line
echo Name: Ameya Shahane
echo Assignment Number: 8.2.1
echo Due Date: May 2, 2017
echo " " # print a blank line

if ( "$1" == "" || "$2" == "" ) then
	echo "Usage: rename oldfilename newfilename"
else
	mv $1 $2
	echo $1 had been renamed $2
	echo here is a listing of the directory:
	ls
endif
